### PR TITLE
fix lint

### PR DESCRIPTION
**Pull request by futuretea**
A little lint fix,hope it's useful.

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@futuretea  Thanks for your contribution! Please sign off your commit using `git -s`.

Example:

image

**Comment by benjaminhuo** [comment]
@futuretea That's a great start to participant into kube-events development, thanks!
@junotx pls review this PR

**Comment by benjaminhuo** [comment]
> @futuretea Thanks for your contribution! Please sign off your commit using `git -s`.
> 
> Example:
> 
> image

git commit -s -m "xxx"

**Comment by futuretea** [comment]
> > @futuretea Thanks for your contribution! Please sign off your commit using `git -s`.
> > Example:
> > image
> 
> git commit -s -m "xxx"

Thank you. It has been recommited.

**Comment by benjaminhuo** [comment]
@futuretea Thanks for the PR , it looks great!

**Pull request merged**
